### ISSUE TITLE
Just wanted to say - thanks for your `clenup` branch! :)

### ISSUE THREAD

**Issue by SunboX** [meltingice/CamanJS#178]

**Comment by SunboX** [comment]
no issue here :smirk:

**Comment by runn1ng** [comment]
Thank you SunboX! Without you, I would never find this branch and would try to get 2 year old code to run 

The old version has memory leaks, but since nobody seemed to care about the code, I didn't want to even report it. But it is fixed in the new branch, and it has *much much* saner API. Great!

And thanks to meltingice for the library, the "old API" is weird and undocumented, the new one rocks. Only if I could *actually* find it anywhere else then randomly here!

**Comment by runn1ng** [comment]
once I get some bitcoins, I will send you some, haha

**Comment by meltingice** [comment]
Haha thanks @runn1ng. This is one of those projects that I got really burnt out on, but I try and find the motivation to work on it from time to time.

I really like where this cleanup branch is going as well. It's not complete yet, which is why I haven't promoted it more, but it does _most_ things well. I want to take this opportunity to experiment with workers again, especially since you can send Uint8Array's to them now without serialization, but if there's enough interest I might just focus on finishing up the rest of the features and coming back to workers in the future.

**Comment by SunboX** [comment]
Nice to hear! Workers are great, if you get some time and motivation that's cool. If not, have fun :smile:

**Comment by runn1ng** [comment]
I sent you some. Not that much, but I don't have that much either, haha.

I used your code on TREZOR homescreen editor here

https://trezor.github.io/homescreen-editor/

**Comment by meltingice** [comment]
@runn1ng pretty cool, thanks for the BTC!
