### ISSUE TITLE
Is this repo active?

### ISSUE THREAD

**Issue by aayushkapoor206** [meltingice/CamanJS#191]
I have to do a lot of client side image manipulations. Is this library still active and can it be used in production? Are there any recent alternatives?

**Comment by meltingice** [comment]
The current master branch is unlikely to change for awhile, but I have been trying to find time to work on the more experimental `cleanup` branch, which contains a lot of backwards incompatible changes. I'm also exploring implementing WebWorkers again since the last time I implemented them, browsers didn't support cool stuff like transferring data ownership or passing UInt8Arrays without serialization (it was strings only).

The current master branch is suitable for production use.
